### ISSUE TITLE
Quote Expectations for Songs

### ISSUE THREAD

**Issue by Syndric** [Keyma-sh/game-tracker#104] opened 2021-09-03 19:29 UTC
**Describe the bug**
The level of grammar expected in quotes is quite vague. This is especially important when submitting songs as quotes. What is expected?

The official google forms page gives only this in terms of grammar:
"_Spell check and grammar check your submissions_"

This allows the submitter to make their own judgments on how grammatically correct a quote is versus how it's said/reflected in the song. I think a clear expectation needs to be made when transcribing quotes to be used for submission.

**Examples:**

*Example 1:*
For my first example, I'll choose a song that when transcribed follows grammatical rules.
https://youtube.com/clip/Ugy0Hreqiq_gpSJpitZ4AaABCQ

Diamond city lights
Illuminate what's inside
And all the love I feel by your side
Decoding these emotions, you're the ocean I wanna dive into tonight

Quote:
"Diamond city lights! Illuminate what's inside and all the love I feel by your side; decoding these emotions, you're the ocean I wanna dive into tonight!"
This grammatically correct quote reflects the lyrics of the song perfectly. If all songs were like this, this issue wouldn't exist.

*Example 2:*
This is a harder quote to balance.
https://youtu.be/g2jyqPOVUHc?t=29

Smile for the camera 'cause the world's on fire
Cheers to the moment when the words rip off
I'll be holding on with you

Dance with the Devil in the pouring rain
Sharks in the water, but it's all the same
I'll be holding on
I'll be holding on with you

Quote:
"Smile for the camera 'cause the world's on fire. Cheers to the moment when the worlds rip off; I'll be holding on with you. Dance with the devil in the pouring rain. Sharks in the water, but it's all the same. I'll be holding on; I'll be holding on with you."
This quote is difficult to balance the musical reflection, flow, and grammatical correctness.

*Keyma.sh Example 3:*

https://www.youtube.com/watch?v=9wiEM0s4aCQ

"Time changed, we're different, but my mind still says redundant things, can I not think? Will you love this part of me? My lover is the day I can't forget. Furthering my distance from you. Realistically I can't leave now but I'm okay as you keep me from going crazy, keep me from going crazy.
Title: Lover Is A Day
Author: Cuco
Contributor: FRUIT#7132

This quote is impossible to balance the musical reflection, flow, and grammatical correctness.

**The Question**
When transcribing a quote for keyma.sh, should priority be given to musical reflection or grammatical correctness and flow? I think it's important to make clear the grammatical requirements for a quote to be approved seem to flex around songs.

**Comment by CameronCT** [comment] 2021-09-03 19:35
The grammatical requirements will always be a grey area and even other games like TypeRacer or Monkeytype probably are suffering the same problem. The issue is, there's no right or wrong answer. 

If we wanted to introduce an actual guideline then we can, but the problem is there's going to be too many varied opinions around this for us to create a clear structure.

**Comment by Syndric** [comment] 2021-09-03 19:38
Would you suggest correcting already existing quotes to balance musical reflection and flow? The problem that I'm seeing is that periods and commas are the only punctuation that people know how to use. Other forms of punctuation do a much better job as I've used in the examples above.

**Comment by CameronCT** [comment] 2021-09-03 19:41
I would say from here on out sure, but it's not something I can expect everyone to perform. Many people in different countries use punctuation differently than what Canada or US could use.

It's basically, you're going to lose correcting them all and it might be more of a waste of time than anything.

**Comment by CameronCT** [comment] 2021-09-03 19:41
Didn't mean to close.

**Comment by Syndric** [comment] 2021-09-04 19:01
Going to add two more things:
1. Replacing too much punctuation in badly transcribed quotes would invalidate wpm leaderboards for the quote
2. This conversation can also be applied to poems which are always weird to put in sentences

**Comment by CameronCT** [comment] 2021-10-07 05:37
Closing since this topic is pretty trivial and hard to enforce by nature. The general rule is make sure it's grammatically correct (unless the specific quote is references certain terms uniquely) and any potential correction in #text-bugs is approached with some form of discussion for each one.

**Closed by CameronCT** 2021-10-07 05:37 UTC
Labels: enhancement
