### ISSUE TITLE
Keyma.sh: Unable to type in learn section

### ISSUE THREAD

**Issue by Faith111111111** [Keyma-sh/game-tracker#94] opened 2021-08-20 00:21 UTC
**Expected behavior**

Unable to type in the learn section. I went into the introduction to QWERTY and I went into the home row but I could not type the letters.

**Screenshots**

![Screenshot (1153)](https://user-images.githubusercontent.com/89229335/130159332-0a46571b-0cfd-451f-8c66-6d63e5e86c8f.png)
29335/130159304-d7576414-037d-4382-afe0-be5944234e9e.png)

[https://keyma.sh/learn/QWERTY_BASIC/0]
**Desktop (please complete the following information):**
 - OS: [e.g. iOS] : Lenovo, OS built 19043.1165, WIndows 10 edition
![Screenshot (1153)](https://user-images.githubusercontent.com/89229335/130159794-d6b3947e-275a-4757-8d52-f81db60ba4e8.png) OR https://keyma.sh/learn/QWERTY_BASIC/0

 - Browser [e.g. chrome, safari]: chrome
 - Version [e.g. 22]: 21H1

**Additional context**

**Comment by cyan-amethyst** [comment] 2021-08-20 00:30
You can still type in the Learn Centre, you just have to manually click on the input box (which is right under the letters/words that you need to type). This issue has been reported before and will be fixed in a future update. Until then, you just have to click on the input box and then start typing as per usual. :)

**Comment by Faith111111111** [comment] 2021-08-20 00:52
yes it works! thank you for your help!

**Comment by CameronCT** [comment] 2021-08-20 01:37
Duplicate of https://github.com/Keyma-sh/game-tracker/issues/68

**Closed by CameronCT** 2021-08-20 01:37 UTC
Labels: bug
